---
- name: Apt Update
  ansible.builtin.apt:
    update_cache: yes

- name: Apt Upgrade
  ansible.builtin.apt:
    upgrade: dist

- name: Install Chromium
  ansible.builtin.apt:
    name: chromium-browser
    state: latest

- name: Install VLC
  snap:
    name: vlc
    classic: yes
